// Coordonnées & informations légales ABICOM SARL (ABILITY COMPANY SARL)
export const site = {
  name: "ABICOM SARL",
  fullName: "ABILITY COMPANY SARL",
  slogan: "Votre Partenaire Minier 100% Congolais",
  tagline:
    "Fourniture de produits chimiques et solutions d'ingénierie pour le secteur minier en RDC et à l'international.",
  contact: {
    responsable: "M. Moussa OTOKO LUSAKUENO",
    role: "C.O et Chef Manager",
    phone: "+243 979 477 708",
    phoneHref: "tel:+243979477708",
    whatsapp: "+243 824 933 331",
    whatsappHref: "https://wa.me/243824933331",
    email: "info@abicom-sarl.com",
    address: "12/B Av. Sola, Golf Météo La Katangaise, C/Annex, Lubumbashi, RDC",
    mapsQuery:
      "12/B Av. Sola, Golf Météo La Katangaise, Lubumbashi, RDC",
    created: "2020",
  },
  legal: {
    rccm: "CD/L'SH/RCCM/20FB-00515",
    nif: "A203616BL",
    tva: "5763/2022",
    cnss: "1018797300",
  },
  socials: [
    { label: "Facebook", href: "https://facebook.com/abicom_sarl", icon: "facebook" },
    { label: "LinkedIn", href: "https://linkedin.com/company/abicom-sarl", icon: "linkedin" },
    { label: "Instagram", href: "https://instagram.com/abicom_sarl", icon: "instagram" },
    { label: "TikTok", href: "https://tiktok.com/@abicom_sarl", icon: "tiktok" },
    { label: "YouTube", href: "https://youtube.com/@abricom_sarl", icon: "youtube" },
    { label: "X", href: "https://x.com/abicom_sarl", icon: "x" },
  ],
  admin: { login: "admin", password: "abic0m2025" },
  // Capacités étendues (ingénierie minière) — issu du catalogue 2026
  capabilities: [
    {
      key: "chemical",
      titleFr: "Fournitures chimiques & minérales",
      titleEn: "Chemical & Mineral Supply",
      itemsFr: ["Acide sulfurique", "Soufre granulaire", "Réactifs spécialisés"],
      itemsEn: ["Sulphuric Acid", "Sulphur Granules", "Specialized Reagents"],
      icon: "flask",
    },
    {
      key: "engineering",
      titleFr: "Ingénierie de base",
      titleEn: "Core Engineering",
      itemsFr: ["Pompes & vannes", "Solutions clés en main", "Systèmes hydrauliques", "Essais & dévasage de pompes"],
      itemsEn: ["Pumps & Valves", "Turnkey Solutions", "Hydraulic Systems", "Pump Testing & Desludging"],
      icon: "gear",
    },
    {
      key: "infra",
      titleFr: "Infrastructure & fabrication",
      titleEn: "Infrastructure & Fabric",
      itemsFr: ["Installation de convoyeurs", "Services de fabrication", "Composants électriques", "Fourniture d'EPI"],
      itemsEn: ["Conveyor Installations", "Fabrication Services", "Electrical Components", "PPE Supply"],
      icon: "build",
    },
    {
      key: "specialized",
      titleFr: "Exploitation minière spécialisée",
      titleEn: "Specialized Mining",
      itemsFr: ["Projection de béton robotisée", "Grandes excavations souterraines", "Développement mécanisé"],
      itemsEn: ["Robotic Shotcreting", "Underground Large Excavations", "Mechanized Development"],
      icon: "robot",
    },
    {
      key: "maintenance",
      titleFr: "Maintenance & assistance",
      titleEn: "Maintenance & Support",
      itemsFr: ["Maintenance des équipements", "Assistance technique", "Assistance technique sur site"],
      itemsEn: ["Equipment Maintenance", "Engineering Support", "On-site Technical Aid"],
      icon: "wrench",
    },
  ],
  pillars: [
    {
      key: "empowerment",
      titleFr: "Autonomisation réelle",
      titleEn: "Real Empowerment",
      descFr: "Développement des compétences locales et croissance communautaire dans chaque projet.",
      descEn: "Local skill development and community growth through every project.",
      icon: "users",
    },
    {
      key: "expertise",
      titleFr: "Expertise pointue",
      titleEn: "High Expertise",
      descFr: "Ingénierie de pointe et technologies modernes pour résoudre les problèmes miniers complexes.",
      descEn: "Advanced engineering knowledge and modern technologies for complex mining issues.",
      icon: "brain",
    },
    {
      key: "energy",
      titleFr: "Dynamisme communicatif",
      titleEn: "Contagious Energy",
      descFr: "Projets menés avec flexibilité, passion et une approche proactive face à chaque défi.",
      descEn: "Projects driven with flexibility, passion and a proactive approach to every challenge.",
      icon: "bolt",
    },
  ],
};
